version: '3.8'

services:
  api:
    container_name: "content_api_app"
    build:
      context: .
    ports:
      - 80:8000
    command:
      sh -c "python run.py migrate && python run.py runserver"
    depends_on:
      - postgres
      - redis
    restart: always

  postgres:
    container_name: "content_db"
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - ./.env.test
    restart: unless-stopped

  redis:
    container_name: "content_redis"
    image: redis:latest
    ports:
      - 6379:6379
    restart: unless-stopped