version: '3.8'

services:
  content_api:
    container_name: "content_api_app"
    build:
      context: .
    ports:
      - 8085:8000
    command:
      sh -c "python run.py migrate && python run.py runserver"
    depends_on:
      - postgres_content
      - redis_content
    restart: always

  
  postgres_content:
    container_name: "postgres_content"
    image: postgres:13.3
    ports:
      - 54328:5432
    env_file:
      - ./.env.test
    restart: unless-stopped

  redis_content:
    container_name: "redis_content"
    image: redis:latest 
    ports:
      - 63790:6379
    restart: unless-stopped